name: CI/CD Tests

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Run Postman CLI tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup project
        run: |
          docker compose up -d
          sleep 60
          docker compose run --rm composer
          docker compose exec -T -u root laravel-api chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache
          docker compose exec -T laravel-api php artisan migrate:fresh --seed --force
      - name: Install Postman
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Test with Postman
        run: |
          postman collection run -d tests/payments_data.csv tests/payments.json -r cli --delay-request 50 -n 1 || true
          postman collection run -d tests/products_data.csv tests/products.json -r cli --delay-request 50 -n 1 || true
          postman collection run -d tests/users_data.csv tests/users.json -r cli --delay-request 50 -n 1 || true
      - name: Cleanup Docker
        if: always()
        run: docker compose down -v
