name: CI/CD Tests

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Docker locally
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup project
        run: |
          docker compose up -d
          sleep 60
          docker compose run --rm composer
          docker compose exec -T -u root laravel-api chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache
          docker compose exec -T laravel-api php artisan migrate:fresh --seed --force

  postman:
    runs-on: ubuntu-latest
    name: Test with Postman
    needs: [deploy]
    steps:
      - name: Install Postman
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Test with Postman
        run: |
          postman collection run tests/pm/payments.json -r cli,html --delay-request 50 || true
          postman collection run tests/pm/products.json -r cli,html --delay-request 50 || true
          postman collection run tests/pm/users.json -r cli,html --delay-request 50 || true

  selenium:
    runs-on: ubuntu-latest
    name: Test with Python and Selenium
    needs: [deploy]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Setup Python venv
        run: |
          python -m venv ./venv
          ./venv/bin/pip install -r requirements.txt

  cleanup:
    runs-on: ubuntu-latest
    name: Cleanup Docker
    if: always()
    steps:
      - name: Cleanup
        run: docker compose down -v
