name: Laugh out loud

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup project
        run: |
          docker compose up -d
          sleep 60
          docker compose run --rm composer
          docker compose exec -T -u root laravel-api chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache
          docker compose exec -T laravel-api php artisan migrate:fresh --seed --force
      - name: Install Postman
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Test with Postman
        run: |
          postman collection run tests/payments.postman_collection.json -r cli,html
      - name: Upload test results
        if: ${{ always() }}
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./postman-cli-reports/
      - name: Cleanup
        if: always()
        run: docker compose down -v
